// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rentals_API_NET6.Context;

#nullable disable

namespace Rentals_API_NET6.Migrations
{
    [DbContext(typeof(RentalsDbContext))]
    [Migration("20220518091142_removeInventory")]
    partial class removeInventory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.AccessoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("AccessoryId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "AccessoryId");

                    b.HasIndex("AccessoryId");

                    b.ToTable("AccessoryItems");

                    b.HasData(
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 13
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 13
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 14
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 14
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 17
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 17
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 24
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 24
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 25
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 25
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 46
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 46
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 48
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 48
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 49
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 49
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 50
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 50
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 51
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 51
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 52
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 52
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 63
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 63
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 64
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 64
                        },
                        new
                        {
                            ItemId = 11,
                            AccessoryId = 69
                        },
                        new
                        {
                            ItemId = 12,
                            AccessoryId = 69
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 69
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 69
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 72
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 72
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 44
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 44
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 61
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 61
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 62
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 62
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 49
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 49
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 53
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 53
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 54
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 54
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 55
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 55
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 48
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 48
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 46
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 46
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 17
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 17
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 22
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 22
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 13
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 13
                        },
                        new
                        {
                            ItemId = 15,
                            AccessoryId = 14
                        },
                        new
                        {
                            ItemId = 16,
                            AccessoryId = 14
                        },
                        new
                        {
                            ItemId = 18,
                            AccessoryId = 47
                        },
                        new
                        {
                            ItemId = 19,
                            AccessoryId = 47
                        },
                        new
                        {
                            ItemId = 20,
                            AccessoryId = 47
                        },
                        new
                        {
                            ItemId = 18,
                            AccessoryId = 57
                        },
                        new
                        {
                            ItemId = 19,
                            AccessoryId = 57
                        },
                        new
                        {
                            ItemId = 20,
                            AccessoryId = 57
                        },
                        new
                        {
                            ItemId = 18,
                            AccessoryId = 58
                        },
                        new
                        {
                            ItemId = 19,
                            AccessoryId = 58
                        },
                        new
                        {
                            ItemId = 20,
                            AccessoryId = 58
                        },
                        new
                        {
                            ItemId = 18,
                            AccessoryId = 59
                        },
                        new
                        {
                            ItemId = 19,
                            AccessoryId = 59
                        },
                        new
                        {
                            ItemId = 20,
                            AccessoryId = 59
                        },
                        new
                        {
                            ItemId = 21,
                            AccessoryId = 57
                        },
                        new
                        {
                            ItemId = 21,
                            AccessoryId = 58
                        },
                        new
                        {
                            ItemId = 21,
                            AccessoryId = 59
                        },
                        new
                        {
                            ItemId = 21,
                            AccessoryId = 47
                        },
                        new
                        {
                            ItemId = 24,
                            AccessoryId = 40
                        },
                        new
                        {
                            ItemId = 25,
                            AccessoryId = 40
                        },
                        new
                        {
                            ItemId = 24,
                            AccessoryId = 41
                        },
                        new
                        {
                            ItemId = 25,
                            AccessoryId = 41
                        },
                        new
                        {
                            ItemId = 24,
                            AccessoryId = 42
                        },
                        new
                        {
                            ItemId = 25,
                            AccessoryId = 42
                        },
                        new
                        {
                            ItemId = 24,
                            AccessoryId = 43
                        },
                        new
                        {
                            ItemId = 25,
                            AccessoryId = 43
                        },
                        new
                        {
                            ItemId = 38,
                            AccessoryId = 40
                        },
                        new
                        {
                            ItemId = 38,
                            AccessoryId = 41
                        },
                        new
                        {
                            ItemId = 38,
                            AccessoryId = 42
                        },
                        new
                        {
                            ItemId = 38,
                            AccessoryId = 43
                        },
                        new
                        {
                            ItemId = 39,
                            AccessoryId = 40
                        },
                        new
                        {
                            ItemId = 39,
                            AccessoryId = 41
                        },
                        new
                        {
                            ItemId = 39,
                            AccessoryId = 42
                        },
                        new
                        {
                            ItemId = 39,
                            AccessoryId = 43
                        },
                        new
                        {
                            ItemId = 45,
                            AccessoryId = 46
                        },
                        new
                        {
                            ItemId = 45,
                            AccessoryId = 48
                        },
                        new
                        {
                            ItemId = 45,
                            AccessoryId = 49
                        },
                        new
                        {
                            ItemId = 61,
                            AccessoryId = 53
                        },
                        new
                        {
                            ItemId = 62,
                            AccessoryId = 53
                        },
                        new
                        {
                            ItemId = 61,
                            AccessoryId = 54
                        },
                        new
                        {
                            ItemId = 62,
                            AccessoryId = 54
                        },
                        new
                        {
                            ItemId = 61,
                            AccessoryId = 55
                        },
                        new
                        {
                            ItemId = 62,
                            AccessoryId = 55
                        },
                        new
                        {
                            ItemId = 63,
                            AccessoryId = 50
                        },
                        new
                        {
                            ItemId = 64,
                            AccessoryId = 50
                        },
                        new
                        {
                            ItemId = 63,
                            AccessoryId = 51
                        },
                        new
                        {
                            ItemId = 64,
                            AccessoryId = 51
                        },
                        new
                        {
                            ItemId = 63,
                            AccessoryId = 52
                        },
                        new
                        {
                            ItemId = 64,
                            AccessoryId = 52
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 26
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 27
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 28
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 29
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 93
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 94
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 95
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 30
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 31
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 32
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 33
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 34
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 35
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 36
                        },
                        new
                        {
                            ItemId = 65,
                            AccessoryId = 37
                        },
                        new
                        {
                            ItemId = 76,
                            AccessoryId = 78
                        },
                        new
                        {
                            ItemId = 77,
                            AccessoryId = 78
                        },
                        new
                        {
                            ItemId = 80,
                            AccessoryId = 60
                        });
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.CartItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Přístroje"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Objektivy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stativy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Příslušenství"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audiotechnika"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ostatní"
                        });
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.FavouriteItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteItems");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentingHistoryLogId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Img");

                    b.HasIndex("RentingHistoryLogId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Kamera",
                            IsDeleted = true,
                            Name = "Kamera",
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Kamera",
                            IsDeleted = true,
                            Name = "Kamera",
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Dobrý zvuk",
                            IsDeleted = true,
                            Name = "Mikrofon",
                            State = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Dobrý zvuk",
                            IsDeleted = true,
                            Name = "Mikrofon",
                            State = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "24,1 Mpx",
                            IsDeleted = true,
                            Name = "Kamera Sony",
                            State = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "24,1 Mpx",
                            IsDeleted = true,
                            Name = "Kamera Sony",
                            State = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "24,1 Mpx",
                            IsDeleted = true,
                            Name = "Kamera Sony",
                            State = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Lehké tělo, kompaktní, s možností až 4K videa",
                            IsDeleted = true,
                            Name = "Zrcadlovka SONY Alpha A6300",
                            State = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Lehké tělo, kompaktní, s možností až 4K videa",
                            IsDeleted = true,
                            Name = "Zrcadlovka SONY Alpha A6300",
                            State = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Lehké tělo, kompaktní, s možností až 4K videa",
                            IsDeleted = true,
                            Name = "Zrcadlovka SONY Alpha A6300",
                            State = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Img = "EOS650D_5a40.jpg",
                            IsDeleted = false,
                            Name = "Fotoaparát Canon EOS 650D",
                            Note = "Bez očnice",
                            State = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Img = "EOS650D_5a40.jpg",
                            IsDeleted = false,
                            Name = "Fotoaparát Canon EOS 650D",
                            Note = "Bez očnice",
                            State = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Img = "Sigma18-50_f918.jpg",
                            IsDeleted = false,
                            Name = "Objektiv SIGMA 17-50 mm 1:2.8",
                            Note = "Prstenec transfokátoru má vůli",
                            State = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Img = "Sigma18-50_f918.jpg",
                            IsDeleted = false,
                            Name = "Objektiv SIGMA 17-50 mm 1:2.8",
                            Note = "Určen primárně do ateliéru!",
                            State = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Img = "EOS70D_b624.jpg",
                            IsDeleted = false,
                            Name = "Fotoaparát Canon EOS 70D",
                            State = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Img = "EOS70D_b624.jpg",
                            IsDeleted = false,
                            Name = "Fotoaparát Canon EOS 70D",
                            Note = "Určen primárně do ateliéru!",
                            State = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "FullFrame objektiv",
                            Img = "Sigma24-70_7bde.jpg",
                            IsDeleted = false,
                            Name = "Objektiv SIGMA 24-70 mm 1:2.8",
                            State = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Stříbrná",
                            IsDeleted = false,
                            Name = "Videokamera Sony 1.9/2.1-57",
                            State = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Stříbrná",
                            IsDeleted = false,
                            Name = "Videokamera Sony 1.9/2.1-57",
                            State = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Stříbrná",
                            IsDeleted = false,
                            Name = "Videokamera Sony 1.9/2.1-57",
                            State = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "F1.8/f1.9-57 (černá)",
                            Img = "SonyHDR-CX320_6824.jpg",
                            IsDeleted = false,
                            Name = "Videokamera Sony HDR-CX320",
                            State = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Img = "gripC70D_2982.jpg",
                            IsDeleted = false,
                            Name = "Bateriový grip Phottix BG 70D",
                            State = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Knoflíková baterie GP Alkaline A76 LR44 V13GA 1.5 V",
                            State = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "90 MB/s",
                            Img = "SDSanDisk64GB_715b.jpg",
                            IsDeleted = false,
                            Name = "SD karta SanDisk 64 GB",
                            State = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "90 MB/s",
                            Img = "SDSanDisk64GB_715b.jpg",
                            IsDeleted = false,
                            Name = "SD karta SanDisk 64 GB",
                            State = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie Alkalisk 1.5 V LR03 AAA Ikea",
                            State = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie Alkalisk 1.5 V LR03 AAA Ikea",
                            State = 0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie Eneloop 1.2 V HR 3UTG AA",
                            State = 0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie Eneloop 1.2 V HR 4UTG AAA",
                            State = 0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AAA",
                            State = 0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AAA",
                            State = 0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AAA",
                            State = 0
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie LSD 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Černý",
                            IsDeleted = true,
                            Name = "MicroSD karta adapter SAMSUNG",
                            State = 0
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "Černý",
                            IsDeleted = false,
                            Name = "SD karta Kingston SD10G3 32 GB",
                            State = 0
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Průhledné",
                            IsDeleted = true,
                            Name = "Pouzdro na SD kartu",
                            State = 0
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Průhledné",
                            IsDeleted = true,
                            Name = "Pouzdro na SD kartu",
                            State = 0
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            Description = "Průhledné",
                            IsDeleted = true,
                            Name = "Pouzdro na SD kartu",
                            State = 0
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Průhledné",
                            IsDeleted = true,
                            Name = "Pouzdro na SD kartu",
                            State = 0
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Description = "FullFrame",
                            Img = "CanonEF70-200_b2f2.jpg",
                            IsDeleted = false,
                            Name = "Objektiv Canon ULTRASONIC 70-200 mm F4",
                            State = 0
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            Description = "Černý",
                            IsDeleted = false,
                            Name = "Fotoaparát Canon EOS 350D",
                            State = 0
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Description = "FullFrame",
                            Img = "CanonEF50_0055.jpg",
                            IsDeleted = false,
                            Name = "Objektiv Canon 50 mm F1.8",
                            State = 0
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = false,
                            Name = "Baterie SONY NP FV70A 1900mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = true,
                            Name = "Baterie Canon LP E6N 1865mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = true,
                            Name = "Baterie Canon LP E6 1800mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "k 650D (šedá)",
                            Img = "BattLPE8_fd96.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E8 1120mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            Description = "k 650D (šedá)",
                            Img = "BattLPE8_fd96.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E8 1120mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 4,
                            Description = "k 650D (šedá)",
                            Img = "BattLPE8_fd96.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E8 1120mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 4,
                            Description = "k C70D, C5D",
                            Img = "BattLPE6_03b5.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E6 1800mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 4,
                            Description = "k C70D, C5D",
                            Img = "BattLPE6_03b5.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E6 1800mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            Description = "k C70D, C5D",
                            Img = "BattLPE6_03b5.jpg",
                            IsDeleted = false,
                            Name = "Baterie Canon LP E6 1800mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = true,
                            Name = "Baterie Canon LP E6 1865mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = false,
                            Name = "Baterie SONY NP FV30 500mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = false,
                            Name = "Baterie SONY NP FV30 500mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = false,
                            Name = "Baterie SONY NP FV30 500mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 4,
                            Description = "náhradní akumulátor",
                            IsDeleted = false,
                            Name = "Baterie Panasonic VW VBN130 1250mAh",
                            State = 0
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 4,
                            Description = "k C70D, C5D",
                            Img = "BattChgLC-E6E_27dd.jpg",
                            IsDeleted = false,
                            Name = "Nabíječka baterií Canon LC E6E",
                            State = 0
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 4,
                            Description = "k C70D, C5D",
                            Img = "BattChgLC-E6E_27dd.jpg",
                            IsDeleted = false,
                            Name = "Nabíječka baterií Canon LC E6E",
                            State = 0
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 4,
                            Description = "k C650D",
                            Img = "BattChgLC-E8E_02bb.jpg",
                            IsDeleted = false,
                            Name = "Nabíječka baterií Canon LC E8E",
                            State = 0
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 4,
                            Description = "k C650D",
                            Img = "BattChgLC-E8E_02bb.jpg",
                            IsDeleted = false,
                            Name = "Nabíječka baterií Canon LC E8E",
                            State = 0
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 4,
                            Description = "Černá",
                            IsDeleted = false,
                            Name = "Nabíječka baterií FK technics BC 450",
                            State = 0
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            Description = "Černý",
                            IsDeleted = true,
                            Name = "Napájecí kabel I SHENG 033",
                            State = 0
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 4,
                            Description = "Černý",
                            IsDeleted = true,
                            Name = "Napájecí kabel I SHENG 033",
                            State = 0
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            IsDeleted = true,
                            Name = "Testujeme s.r.o.",
                            State = 0
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            Description = "(Kz)",
                            Img = "Sigma18-200_cd74.jpg",
                            IsDeleted = false,
                            Name = "Objektiv SIGMA 18-200 mm 1:3.5-6.3",
                            State = 0
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 3,
                            Img = "StativVelbonC-600_b14c.jpg",
                            IsDeleted = false,
                            Name = "Stativ Velbon C-600",
                            Note = "xxx 2308",
                            State = 0
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 3,
                            Img = "StativVelbonC-600_b14c.jpg",
                            IsDeleted = false,
                            Name = "Stativ Velbon C-600",
                            State = 0
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 4,
                            Description = "95 MB/s",
                            Img = "SDLexar64GB_e4c2.jpg",
                            IsDeleted = false,
                            Name = "SD karta Lexar 64GB",
                            State = 0
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 6,
                            Description = "Rezervace místnosti se studiovými světly a odpalovačem.",
                            Img = "atelier_a27b.jpg",
                            IsDeleted = false,
                            Name = "Ateliér B210",
                            State = 0
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 3,
                            Description = "Hlava má vůli; nevhodný na video",
                            Img = "hamaStar62_914d.jpg",
                            IsDeleted = false,
                            Name = "Stativ Hama Star 62",
                            State = 0
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 3,
                            Description = "Steadicam Camtree Wonder-3",
                            Img = "flycam_fd0f.jpg",
                            IsDeleted = false,
                            Name = "Flycam HD-3000",
                            State = 0
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 5,
                            Img = "ZoomH1_2ffd.jpg",
                            IsDeleted = false,
                            Name = "Rekordér Zoom H1",
                            State = 0
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 5,
                            Img = "ZoomH1_2ffd.jpg",
                            IsDeleted = false,
                            Name = "Rekordér Zoom H1",
                            State = 0
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            Img = "MiniTripod_92cc.jpg",
                            IsDeleted = false,
                            Name = "stativ MiniTripod plochý",
                            State = 0
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 2,
                            Img = "Sigma30_0caf.jpg",
                            IsDeleted = false,
                            Name = "Objektiv Sigma 30mm/F1.4",
                            State = 0
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 1,
                            Description = "F1,5 f2,84-34,1mm (včetně akumulátoru)",
                            Img = "Panasonic_HC-X920_7ce7.jpg",
                            IsDeleted = false,
                            Name = "Videokamera Panasonic HC-X920",
                            State = 0
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 3,
                            Img = "RigSpider_ea93.jpg",
                            IsDeleted = false,
                            Name = "Stativ Rig Spider FT-10",
                            State = 0
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            Img = "RigSpider_ea93.jpg",
                            IsDeleted = false,
                            Name = "Stativ Rig Spider FT-10",
                            State = 0
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 3,
                            Img = "RigSpider_ea93.jpg",
                            IsDeleted = false,
                            Name = "Stativ Rig Spider FT-10",
                            State = 0
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 3,
                            Description = "(kulová hlava)",
                            Img = "StativMS-007H_3d14.jpg",
                            IsDeleted = false,
                            Name = "Stativ video MS-007H",
                            Note = "poškozen zip",
                            State = 0
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 5,
                            Description = "bez předzesilovače, induktivní",
                            Img = "MikrofonKlopový_97b3.jpg",
                            IsDeleted = false,
                            Name = "Mikrofon klopový",
                            State = 0
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 5,
                            Description = "bez předzesilovače, induktivní",
                            Img = "MikrofonKlopový_97b3.jpg",
                            IsDeleted = false,
                            Name = "Mikrofon klopový",
                            State = 0
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            Img = "SonyVct-d680rm_9d51.jpg",
                            IsDeleted = false,
                            Name = "Stativ Sony VCT-D680RM",
                            State = 0
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 6,
                            Description = "Tento výrobek je zkonstruován z tenkého plátu ocelového plechu, který má patinovaný povrch. Díky tomuto hrubému povrchu působí výrobek surově, ale zároveň kvůli jednoduché až primitivní konstrukci nabývá minimalistického a elegantního vzhledu. ",
                            Img = "tn-techtips_f9dd.jpg",
                            IsDeleted = true,
                            Name = "zkušební předmět",
                            Note = "první předmět",
                            State = 0
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 6,
                            Description = "Tento výrobek je zkonstruován z tenkého plátu ocelového plechu, který má patinovaný povrch. Díky tomuto hrubému povrchu působí výrobek surově, ale zároveň kvůli jednoduché až primitivní konstrukci nabývá minimalistického a elegantního vzhledu. ",
                            Img = "kitt-design-illustration_73ad.png",
                            IsDeleted = true,
                            Name = "zkušební předmět",
                            Note = "druhý předmět",
                            State = 0
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 6,
                            Description = "Tento výrobek je zkonstruován z tenkého plátu ocelového plechu, který má patinovaný povrch. Díky tomuto hrubému povrchu působí výrobek surově, ale zároveň kvůli jednoduché až primitivní konstrukci nabývá minimalistického a elegantního vzhledu. ",
                            Img = "tn-techtips_f9dd.jpg",
                            IsDeleted = true,
                            Name = "zkušební předmět",
                            State = 0
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 6,
                            Description = "Tento výrobek je zkonstruován z tenkého plátu ocelového plechu, který má patinovaný povrch. Díky tomuto hrubému povrchu působí výrobek surově, ale zároveň kvůli jednoduché konstrukci nabývá minimalistického a elegantního vzhledu. ",
                            IsDeleted = true,
                            Name = "Fiktivní předmět",
                            State = 0
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 6,
                            Description = "Tento výrobek je zkonstruován z tenkého plátu ocelového plechu, který má patinovaný povrch. Díky tomuto hrubému povrchu působí výrobek surově, ale zároveň kvůli jednoduché konstrukci nabývá minimalistického a elegantního vzhledu. ",
                            IsDeleted = true,
                            Name = "Fiktivní předmět",
                            State = 0
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie GP 2700 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie GP 2700 1.2 V AA",
                            State = 0
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 4,
                            IsDeleted = true,
                            Name = "Alkalická baterie GP 2700 1.2 V AA",
                            State = 0
                        });
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ItemHistoryLogs");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChangedProperty")
                        .HasColumnType("int");

                    b.Property<string>("ChangedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemHistoryLogId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemHistoryLogId");

                    b.ToTable("ItemChanges");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemChangeConnection", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemChangeId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "ItemChangeId");

                    b.HasIndex("ItemChangeId");

                    b.ToTable("ItemChangeConnections");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemPreChangeConnection", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemChangeId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "ItemChangeId");

                    b.HasIndex("ItemChangeId");

                    b.ToTable("ItemPreChangeConnections");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Renting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ApproverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Rentings");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.RentingHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentingId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentingId");

                    b.HasIndex("UserId");

                    b.ToTable("RentingHistoryLogs");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.RentingItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("RentingId")
                        .HasColumnType("int");

                    b.Property<bool>("Returned")
                        .HasColumnType("bit");

                    b.HasKey("ItemId", "RentingId");

                    b.HasIndex("RentingId");

                    b.ToTable("RentingItems");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.UploadedFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = "AsteroidSprite_ddff.png",
                            ContentType = "image/png",
                            OriginalName = "AsteroidSprite_ddff.png"
                        },
                        new
                        {
                            Id = "atelier_a27b.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "atelier_a27b.jpg"
                        },
                        new
                        {
                            Id = "BattChgLC-E6E_27dd.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "BattChgLC-E6E_27dd.jpg"
                        },
                        new
                        {
                            Id = "BattChgLC-E8E_02bb.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "BattChgLC-E8E_02bb.jpg"
                        },
                        new
                        {
                            Id = "BattLPE6_03b5.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "BattLPE6_03b5.jpg"
                        },
                        new
                        {
                            Id = "BattLPE8_fd96.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "BattLPE8_fd96.jpg"
                        },
                        new
                        {
                            Id = "CanonEF50_0055.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "CanonEF50_0055.jpg"
                        },
                        new
                        {
                            Id = "CanonEF70-200_b2f2.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "CanonEF70-200_b2f2.jpg"
                        },
                        new
                        {
                            Id = "comica1_5b38.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "comica1_5b38.jpg"
                        },
                        new
                        {
                            Id = "comica2_ed64.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "comica2_ed64.jpg"
                        },
                        new
                        {
                            Id = "crane3Lab_1685.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "crane3Lab_1685.jpg"
                        },
                        new
                        {
                            Id = "Cullmann3400_cd56.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Cullmann3400_cd56.jpg"
                        },
                        new
                        {
                            Id = "cvm-d02_8d19.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "cvm-d02_8d19.jpg"
                        },
                        new
                        {
                            Id = "deity_v-mic-d3_e4bb.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "deity_v-mic-d3_e4bb.jpg"
                        },
                        new
                        {
                            Id = "e890d2d1-ce7d-4b33-98ff-851e85ac4fd2_940c.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "e890d2d1-ce7d-4b33-98ff-851e85ac4fd2_940c.jpg"
                        },
                        new
                        {
                            Id = "e890d2d1-ce7d-4b33-98ff-851e85ac4fd2_b249.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "e890d2d1-ce7d-4b33-98ff-851e85ac4fd2_b249.jpg"
                        },
                        new
                        {
                            Id = "EOS_RP_e3fe.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "EOS_RP_e3fe.jpg"
                        },
                        new
                        {
                            Id = "EOS650D_5a40.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "EOS650D_5a40.jpg"
                        },
                        new
                        {
                            Id = "EOS70D_b624.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "EOS70D_b624.jpg"
                        },
                        new
                        {
                            Id = "EOS90D_7dd9.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "EOS90D_7dd9.jpg"
                        },
                        new
                        {
                            Id = "flycam_fd0f.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "flycam_fd0f.jpg"
                        },
                        new
                        {
                            Id = "gripC70D_2982.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "gripC70D_2982.jpg"
                        },
                        new
                        {
                            Id = "Group 1_0aad.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Group 1_0aad.jpg"
                        },
                        new
                        {
                            Id = "Group 612_3ac5.png",
                            ContentType = "image/png",
                            OriginalName = "Group 612_3ac5.png"
                        },
                        new
                        {
                            Id = "hamaStar62_914d.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "hamaStar62_914d.jpg"
                        },
                        new
                        {
                            Id = "img_2_46b9.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "img_2_46b9.jpg"
                        },
                        new
                        {
                            Id = "img_2_de6d.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "img_2_de6d.jpg"
                        },
                        new
                        {
                            Id = "kitt-design-illustration_73ad.png",
                            ContentType = "image/png",
                            OriginalName = "kitt-design-illustration_73ad.png"
                        },
                        new
                        {
                            Id = "MikrofonKlopový_97b3.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "MikrofonKlopový_97b3.jpg"
                        },
                        new
                        {
                            Id = "MiniTripod_92cc.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "MiniTripod_92cc.jpg"
                        },
                        new
                        {
                            Id = "moza_912f.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "moza_912f.jpg"
                        },
                        new
                        {
                            Id = "Panasonic_HC-X920_7ce7.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Panasonic_HC-X920_7ce7.jpg"
                        },
                        new
                        {
                            Id = "PanasonicVW-CT45E_cd22.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "PanasonicVW-CT45E_cd22.jpg"
                        },
                        new
                        {
                            Id = "Placeholder.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Placeholder.jpg"
                        },
                        new
                        {
                            Id = "rigHawk_8fd1.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "rigHawk_8fd1.jpg"
                        },
                        new
                        {
                            Id = "RigSpider_ea93.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "RigSpider_ea93.jpg"
                        },
                        new
                        {
                            Id = "SDLexar64GB_e4c2.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "SDLexar64GB_e4c2.jpg"
                        },
                        new
                        {
                            Id = "SDSanDisk64GB_2b06.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "SDSanDisk64GB_2b06.jpg"
                        },
                        new
                        {
                            Id = "SDSanDisk64GB_715b.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "SDSanDisk64GB_715b.jpg"
                        },
                        new
                        {
                            Id = "Sigma18-200_cd74.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Sigma18-200_cd74.jpg"
                        },
                        new
                        {
                            Id = "Sigma18-50_f918.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Sigma18-50_f918.jpg"
                        },
                        new
                        {
                            Id = "Sigma24-70_7bde.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Sigma24-70_7bde.jpg"
                        },
                        new
                        {
                            Id = "Sigma30_0caf.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Sigma30_0caf.jpg"
                        },
                        new
                        {
                            Id = "snoppa_4626.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "snoppa_4626.jpg"
                        },
                        new
                        {
                            Id = "SonyHDR-CX320_6824.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "SonyHDR-CX320_6824.jpg"
                        },
                        new
                        {
                            Id = "SonyVct-d680rm_9d51.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "SonyVct-d680rm_9d51.jpg"
                        },
                        new
                        {
                            Id = "StativMS-007H_3d14.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "StativMS-007H_3d14.jpg"
                        },
                        new
                        {
                            Id = "StativMS-007H_3d14_d8f7.png",
                            ContentType = "image/png",
                            OriginalName = "StativMS-007H_3d14_d8f7.png"
                        },
                        new
                        {
                            Id = "stativ-svetlo_98ea.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "stativ-svetlo_98ea.jpg"
                        },
                        new
                        {
                            Id = "StativVelbonC-600_b14c.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "StativVelbonC-600_b14c.jpg"
                        },
                        new
                        {
                            Id = "tn-techtips_f9dd.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "tn-techtips_f9dd.jpg"
                        },
                        new
                        {
                            Id = "Viltrox_f0a5.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "Viltrox_f0a5.jpg"
                        },
                        new
                        {
                            Id = "ZoomH1_2ffd.jpg",
                            ContentType = "image/jpeg",
                            OriginalName = "ZoomH1_2ffd.jpg"
                        });
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OauthId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trustfulness")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOfEntry")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OauthId")
                        .IsUnique()
                        .HasFilter("[OauthId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.AccessoryItem", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("Accessories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.CartItem", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("Carts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "User")
                        .WithMany("Cart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.FavouriteItem", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("Favourites")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "User")
                        .WithMany("Favourite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Item", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.UploadedFile", "ImgFile")
                        .WithMany("Items")
                        .HasForeignKey("Img");

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.RentingHistoryLog", null)
                        .WithMany("ReturnedItems")
                        .HasForeignKey("RentingHistoryLogId");

                    b.Navigation("Category");

                    b.Navigation("ImgFile");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemHistoryLog", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemChange", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.ItemHistoryLog", "ItemHistoryLog")
                        .WithMany("ItemChanges")
                        .HasForeignKey("ItemHistoryLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemHistoryLog");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemChangeConnection", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.ItemChange", "ItemChange")
                        .WithMany("ChangedAccessories")
                        .HasForeignKey("ItemChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("ChangeAccessory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemChange");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemPreChangeConnection", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.ItemChange", "ItemChange")
                        .WithMany("PreviousAccessories")
                        .HasForeignKey("ItemChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("PreChangeAccessory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemChange");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Renting", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "Owner")
                        .WithMany("Rentings")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.RentingHistoryLog", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Renting", "Renting")
                        .WithMany("Logs")
                        .HasForeignKey("RentingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Renting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.RentingItem", b =>
                {
                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Item", "Item")
                        .WithMany("Rentings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rentals_API_NET6.Models.DatabaseModel.Renting", "Renting")
                        .WithMany("Items")
                        .HasForeignKey("RentingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Renting");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Item", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Carts");

                    b.Navigation("ChangeAccessory");

                    b.Navigation("Favourites");

                    b.Navigation("Logs");

                    b.Navigation("PreChangeAccessory");

                    b.Navigation("Rentings");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemHistoryLog", b =>
                {
                    b.Navigation("ItemChanges");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.ItemChange", b =>
                {
                    b.Navigation("ChangedAccessories");

                    b.Navigation("PreviousAccessories");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.Renting", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.RentingHistoryLog", b =>
                {
                    b.Navigation("ReturnedItems");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.UploadedFile", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Rentals_API_NET6.Models.DatabaseModel.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Favourite");

                    b.Navigation("Logs");

                    b.Navigation("Rentings");
                });
#pragma warning restore 612, 618
        }
    }
}
